spring:
    datasource:
        url: jdbc:mysql://localhost:3306/renren_fast?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: renren
        password: 123456
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
# FastDFS 服务配置
fdfs:
    network-timeout: 5
    connect-timeout: 30
    tracker-server:
        - 177.77.77.159:22122
    charset: UTF-8
    tracker-http-port: 8080
    anti-steal-token: false
    secret-key: FastDFS1234567890